name: Create release

on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  Build:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Rust
        uses: actions/setup-rust@v1
        with:
          toolchain: stable

      - name: build
        run: 	mkdir build && cargo build -r --target-dir build/ 


      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dungeonsprawler
          path: build/release/dungeonsprawler

  release:
    name: Upload artifacts to release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3

      - name: Upload artifacts to GitHub Releases
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPO: ${{ github.repository }}
          RELEASE_ID: ${{ github.event.release.id }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${GITHUB_REPOSITORY#*/} ${tag#v}" \
              --generate-notes \
              dungeonsprawler